# Inserts Stripe "Buy Now" / "Reserve with Deposit" buttons into the catalog pages,
# using the payment links generated by create-stripe-links.ps1.
# Idempotent: strips any previously inserted buttons before inserting fresh ones.

param(
  [ValidateSet("test", "live")]
  [string]$Mode = "test"
)

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot
$linksPath = Join-Path $root "stripe_links.$Mode.json"
$links = Get-Content $linksPath -Raw | ConvertFrom-Json
Write-Host "Mode: $Mode (reading $linksPath)"

function Format-Money($n) {
  return "{0:N0}" -f $n
}

$byFile = $links | Group-Object -Property file

foreach ($group in $byFile) {
  $file = Join-Path $root $group.Name
  $rawLines = [string[]]([string[]](Get-Content -Path $file -Encoding UTF8) | Where-Object { $_ -notmatch 'class="btn btn-buy' -and $_ -notmatch 'class="deposit-note"' })
  $lines = [System.Collections.Generic.List[string]]::new($rawLines)
  $items = $group.Group

  for ($i = 0; $i -lt $lines.Count; $i++) {
    $line = $lines[$i]
    $normalized = ($line.Trim() -replace '&ndash;', '-' -replace '&mdash;', '--')

    foreach ($item in $items) {
      $isGridMatch = $normalized -eq "<h3>$($item.name)</h3>"
      $isFeaturedMatch = $normalized -eq "<h2 class=`"section-title`">$($item.name)</h2>"

      if ($isGridMatch -or $isFeaturedMatch) {
        # price line is the next line
        $priceLineIdx = $i + 1
        $priceLine = $lines[$priceLineIdx]
        $indent = ($priceLine -replace '^(\s*)<p.*$', '$1')

        if ($item.mode -eq "deposit") {
          # Reserve/deposit buttons have been removed from the site; skip these items.
          Write-Host "Skipped deposit item $($item.name) (reserve buttons disabled)"
          break
        } else {
          # Buy Now buttons removed from the site; skip these items.
          Write-Host "Skipped $($item.name) (Buy Now disabled)"
          break
          $note = $null
        }

        $buyLink = "$indent<a href=`"$($item.payment_link)`" target=`"_blank`" rel=`"noopener`" class=`"btn btn-buy btn-block`">$label</a>"

        $insertAt = $priceLineIdx + 1
        $lines.Insert($insertAt, $buyLink)
        if ($note) {
          $lines.Insert($insertAt + 1, $note)
        }

        Write-Host "Inserted button for $($item.name) in $($group.Name)"
        break
      }
    }
  }

  $content = [string]::Join("`n", $lines) + "`n"
  [System.IO.File]::WriteAllText($file, $content, (New-Object System.Text.UTF8Encoding($false)))
}

Write-Host "`nDone."
